name: Sync with Replit

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Replit CLI
        run: npm install -g @replit/cli

      - name: Log in to Replit
        run: |
          echo "${{ secrets.REPLIT_TOKEN }}" > replit_token.txt
          repl auth login --token-file replit_token.txt

      - name: Push to Replit
        run: |
          repl push --yes